import { getClass } from './functions';

( ( d ) => {
	/*
	*
	* Adds ability to tab through hidden sub-menu items via keyboard.
	*
	*/
	// Get all top-level anchors.
	const childNavLinks = d.querySelectorAll( '#primary-menu > ul > li > a' );

	// If they exist.
	if ( childNavLinks ) {
		// Run through each of them.
		childNavLinks.forEach( childNavLink => {
			// Set them up with a focus eventListener.
			childNavLink.addEventListener( 'focus', () => {
				// Get the class generated by WP when an li has children.
				const subMenuClass = getClass( 'page_item_has_children', childNavLink.parentNode.classList );

				// Hide all child-menus by default.
				d.querySelectorAll( '.children' ).forEach( subMenu => {
					subMenu.style.display = '';
				} );

				// If the parent li of the current anchor being focus has children.
				if ( 'page_item_has_children' === subMenuClass ) {
					// Find the closest parent child-menu.
					const siblingSubMenu = childNavLink.parentNode.querySelector( '.children' );
					// Set it to display.
					siblingSubMenu.style.display = 'block';
				}

			} );
		} );
	}

} )( document );
